//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetCentar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VetCentar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vet centar - admin dio.
        /// </summary>
        public static string Admin_naslov {
            get {
                return ResourceManager.GetString("Admin_naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Adresa {
            get {
                return ResourceManager.GetString("Adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviraj.
        /// </summary>
        public static string Aktiviraj {
            get {
                return ResourceManager.GetString("Aktiviraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivni nalozi.
        /// </summary>
        public static string Aktivni_nalozi {
            get {
                return ResourceManager.GetString("Aktivni_nalozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite vrstu ljubimca.
        /// </summary>
        public static string Biranje_vrste {
            get {
                return ResourceManager.GetString("Biranje_vrste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum pregleda.
        /// </summary>
        public static string Datum_pregleda {
            get {
                return ResourceManager.GetString("Datum_pregleda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string Datum_rođenja {
            get {
                return ResourceManager.GetString("Datum_rođenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiviraj.
        /// </summary>
        public static string Deaktiviraj {
            get {
                return ResourceManager.GetString("Deaktiviraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivirani nalozi.
        /// </summary>
        public static string Deaktivirani_nalozi {
            get {
                return ResourceManager.GetString("Deaktivirani_nalozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Detalji {
            get {
                return ResourceManager.GetString("Detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji nalaza.
        /// </summary>
        public static string Detalji_nalaza {
            get {
                return ResourceManager.GetString("Detalji_nalaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijagnoza.
        /// </summary>
        public static string Dijagnoza {
            get {
                return ResourceManager.GetString("Dijagnoza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje lijeka.
        /// </summary>
        public static string Dodavanje_lijeka {
            get {
                return ResourceManager.GetString("Dodavanje_lijeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje ljubimca.
        /// </summary>
        public static string Dodavanje_ljubimca {
            get {
                return ResourceManager.GetString("Dodavanje_ljubimca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje vlasnika.
        /// </summary>
        public static string Dodavanje_vlasnika {
            get {
                return ResourceManager.GetString("Dodavanje_vlasnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje vrste.
        /// </summary>
        public static string Dodavanje_vrste {
            get {
                return ResourceManager.GetString("Dodavanje_vrste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje zaposlenog.
        /// </summary>
        public static string Dodavanje_zaposlenog {
            get {
                return ResourceManager.GetString("Dodavanje_zaposlenog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupni lijekovi.
        /// </summary>
        public static string Dostupni_lijekovi {
            get {
                return ResourceManager.GetString("Dostupni_lijekovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Engleski.
        /// </summary>
        public static string Engleski {
            get {
                return ResourceManager.GetString("Engleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseno korisničko ime ili lozinka nisu ispravni..
        /// </summary>
        public static string Greška_nema {
            get {
                return ResourceManager.GetString("Greška_nema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste unijeli korisničko ime ili lozinku..
        /// </summary>
        public static string Greška_prazno {
            get {
                return ResourceManager.GetString("Greška_prazno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Izgled.
        /// </summary>
        public static string Izgled {
            get {
                return ResourceManager.GetString("Izgled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni.
        /// </summary>
        public static string Izmijeni {
            get {
                return ResourceManager.GetString("Izmijeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena lijeka.
        /// </summary>
        public static string Izmjena_lijeka {
            get {
                return ResourceManager.GetString("Izmjena_lijeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena ljubimca.
        /// </summary>
        public static string Izmjena_ljubimca {
            get {
                return ResourceManager.GetString("Izmjena_ljubimca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena vlasnika.
        /// </summary>
        public static string Izmjena_vlasnika {
            get {
                return ResourceManager.GetString("Izmjena_vlasnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena vrste.
        /// </summary>
        public static string Izmjena_vrste {
            get {
                return ResourceManager.GetString("Izmjena_vrste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena zaposlenog.
        /// </summary>
        public static string Izmjena_zaposlenog {
            get {
                return ResourceManager.GetString("Izmjena_zaposlenog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Jezik.
        /// </summary>
        public static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG.
        /// </summary>
        public static string Jmbg {
            get {
                return ResourceManager.GetString("Jmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina.
        /// </summary>
        public static string Količina {
            get {
                return ResourceManager.GetString("Količina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina lijeka.
        /// </summary>
        public static string Količina_lijeka {
            get {
                return ResourceManager.GetString("Količina_lijeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string Korisničko_ime {
            get {
                return ResourceManager.GetString("Korisničko_ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korišteni lijekovi.
        /// </summary>
        public static string Korišteni_lijekovi {
            get {
                return ResourceManager.GetString("Korišteni_lijekovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijekovi.
        /// </summary>
        public static string Lijekovi {
            get {
                return ResourceManager.GetString("Lijekovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljubimci.
        /// </summary>
        public static string Ljubimci {
            get {
                return ResourceManager.GetString("Ljubimci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Lozinka {
            get {
                return ResourceManager.GetString("Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mačka.
        /// </summary>
        public static string Mačka {
            get {
                return ResourceManager.GetString("Mačka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalazi.
        /// </summary>
        public static string Nalazi {
            get {
                return ResourceManager.GetString("Nalazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Naziv {
            get {
                return ResourceManager.GetString("Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VET CENTAR.
        /// </summary>
        public static string Naziv_aplikacije {
            get {
                return ResourceManager.GetString("Naziv_aplikacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije unesena količina..
        /// </summary>
        public static string Nema_vrijednosti {
            get {
                return ResourceManager.GetString("Nema_vrijednosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspješna akcija.
        /// </summary>
        public static string Neuspješna_akcija {
            get {
                return ResourceManager.GetString("Neuspješna_akcija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesena vrijednost nije broj..
        /// </summary>
        public static string Nije_broj {
            get {
                return ResourceManager.GetString("Nije_broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali količinu..
        /// </summary>
        public static string Niste_izabrali_količinu {
            get {
                return ResourceManager.GetString("Niste_izabrali_količinu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali lijek..
        /// </summary>
        public static string Niste_izabrali_lijek {
            get {
                return ResourceManager.GetString("Niste_izabrali_lijek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali ljubimca..
        /// </summary>
        public static string Niste_izabrali_ljubimca {
            get {
                return ResourceManager.GetString("Niste_izabrali_ljubimca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali nalaz..
        /// </summary>
        public static string Niste_izabrali_nalaz {
            get {
                return ResourceManager.GetString("Niste_izabrali_nalaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali vlasnika..
        /// </summary>
        public static string Niste_izabrali_vlasnika {
            get {
                return ResourceManager.GetString("Niste_izabrali_vlasnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali vrstu..
        /// </summary>
        public static string Niste_izabrali_vrstu {
            get {
                return ResourceManager.GetString("Niste_izabrali_vrstu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali zaposlenog..
        /// </summary>
        public static string Niste_izabrali_zaposlenog {
            get {
                return ResourceManager.GetString("Niste_izabrali_zaposlenog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string Nova_lozinka {
            get {
                return ResourceManager.GetString("Nova_lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi nalaz.
        /// </summary>
        public static string Novi_nalaz {
            get {
                return ResourceManager.GetString("Novi_nalaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string Odjava {
            get {
                return ResourceManager.GetString("Odjava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni?.
        /// </summary>
        public static string Odluka {
            get {
                return ResourceManager.GetString("Odluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Opis {
            get {
                return ResourceManager.GetString("Opis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pas.
        /// </summary>
        public static string Pas {
            get {
                return ResourceManager.GetString("Pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        public static string Pol {
            get {
                return ResourceManager.GetString("Pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisu dobro unesena sva polja..
        /// </summary>
        public static string Popunjena_polja {
            get {
                return ResourceManager.GetString("Popunjena_polja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledaj ljubimca.
        /// </summary>
        public static string Pregledaj_ljubimca {
            get {
                return ResourceManager.GetString("Pregledaj_ljubimca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string Pregledi {
            get {
                return ResourceManager.GetString("Pregledi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string Prijava {
            get {
                return ResourceManager.GetString("Prijava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string Prijavi_se {
            get {
                return ResourceManager.GetString("Prijavi_se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasa.
        /// </summary>
        public static string Rasa {
            get {
                return ResourceManager.GetString("Rasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Sačuvaj {
            get {
                return ResourceManager.GetString("Sačuvaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Srpski.
        /// </summary>
        public static string Srpski {
            get {
                return ResourceManager.GetString("Srpski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stručna sprema.
        /// </summary>
        public static string Stručna_sprema {
            get {
                return ResourceManager.GetString("Stručna_sprema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tema 1.
        /// </summary>
        public static string Tema1 {
            get {
                return ResourceManager.GetString("Tema1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tema 2.
        /// </summary>
        public static string Tema2 {
            get {
                return ResourceManager.GetString("Tema2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tema 3.
        /// </summary>
        public static string Tema3 {
            get {
                return ResourceManager.GetString("Tema3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Težina.
        /// </summary>
        public static string Težina {
            get {
                return ResourceManager.GetString("Težina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string Ukloni {
            get {
                return ResourceManager.GetString("Ukloni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime za pretragu.
        /// </summary>
        public static string Unesite_ime_za_pretragu {
            get {
                return ResourceManager.GetString("Unesite_ime_za_pretragu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite naziv za pretragu.
        /// </summary>
        public static string Unesite_naziv_za_pretragu {
            get {
                return ResourceManager.GetString("Unesite_naziv_za_pretragu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite količinu.
        /// </summary>
        public static string Upisivanje_količine {
            get {
                return ResourceManager.GetString("Upisivanje_količine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješna akcija.
        /// </summary>
        public static string Uspješna_akcija {
            get {
                return ResourceManager.GetString("Uspješna_akcija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzimanje lijeka.
        /// </summary>
        public static string Uzimanje_lijeka {
            get {
                return ResourceManager.GetString("Uzimanje_lijeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmi lijek.
        /// </summary>
        public static string Uzmi_lijek {
            get {
                return ResourceManager.GetString("Uzmi_lijek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vet centar - vet dio.
        /// </summary>
        public static string Vet_naslov {
            get {
                return ResourceManager.GetString("Vet_naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinar.
        /// </summary>
        public static string Veterinar {
            get {
                return ResourceManager.GetString("Veterinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visina.
        /// </summary>
        public static string Visina {
            get {
                return ResourceManager.GetString("Visina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlasnici.
        /// </summary>
        public static string Vlasnici {
            get {
                return ResourceManager.GetString("Vlasnici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlasnici ljubimaca.
        /// </summary>
        public static string Vlasnici_ljubimaca {
            get {
                return ResourceManager.GetString("Vlasnici_ljubimaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlasnik.
        /// </summary>
        public static string Vlasnik {
            get {
                return ResourceManager.GetString("Vlasnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta.
        /// </summary>
        public static string Vrsta {
            get {
                return ResourceManager.GetString("Vrsta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrste ljubimaca.
        /// </summary>
        public static string Vrste_ljubimaca {
            get {
                return ResourceManager.GetString("Vrste_ljubimaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ž.
        /// </summary>
        public static string Ž {
            get {
                return ResourceManager.GetString("Ž", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni.
        /// </summary>
        public static string Zaposleni {
            get {
                return ResourceManager.GetString("Zaposleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravstveni karton.
        /// </summary>
        public static string Zdravstveni_karton {
            get {
                return ResourceManager.GetString("Zdravstveni_karton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zec.
        /// </summary>
        public static string Zec {
            get {
                return ResourceManager.GetString("Zec", resourceCulture);
            }
        }
    }
}
